# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1599c79868b69e6969d7efc8a4bbec3b4a93ac82d8c474e634504741c1238c06793c2cdeeadf008b4d7516d3468222f75c75e45cb5a5ea052c50e3f5cd8c4b0

test:
  secret_key_base: c54f3719516b214c51c0e0034efc687b578e0d344f4f36e5bf3b03ac411605e9798980958d492031d39c27876eea8f4057db28c9a84bddb19fb7aef8ac15ba88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
